service: sms-metric

provider:
  name: aws
  runtime: ruby2.7

  stage: ${opt:stage, 'deveropment'}
  region: ap-northeast-1
  profile: ${self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'cloudwatch:GetMetricData'
      Resource:
        '*'
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
      Resource:
        Fn::Join:
          - ':'
          - - arn:aws:dynamodb
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - Fn::Join:
                - '/'
                - - table
                  - Ref: SmsSpentUsd

functions:
  store:
    handler: handler.store
    environment:
      TABLE_NAME: {Ref: SmsSpentUsd}
#    events:
#      - schedule: rate(10 minutes)

resources:
  Resources:
    SmsSpentUsd:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}_sms_spent_usd
        AttributeDefinitions:
        - AttributeName: timestamp
          AttributeType: S
        KeySchema:
        - AttributeName: timestamp
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
